accounts/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name='list'),
    path('create/', views.article_create, name='create'),
    path('<slug:slug>/', views.article_detail, name='detail'),
]

djangonautic/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about),
    path('', article_views.article_list, name='home'),
    path('articles/', include("articles.urls")),
    path('accounts/', include("accounts.urls")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'


class Test(models.Model):
    body = models.TextField()
    title = models.CharField(max_length=100, default='default')

    def __str__(self):
        return self.title

articles/forms.py
from django import forms
from . import models


class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb']

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


# Create your views here.


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        login_var = AuthenticationForm(data=request.POST)
        if login_var.is_valid():
            # log in the user
            user = login_var.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')

    else:
        login_var = AuthenticationForm()
    return render(request, 'accounts/login.html', {'login_var': login_var})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render, redirect
from .models import Article, Test
from django.contrib.auth.decorators import login_required
# Create your views here.
from . import forms

def article_list(request):
    articles = Article.objects.all().order_by('date')
    test = Test.objects.all()
    return render(request, "articles/article_list.html", {'articles': articles, 'test':test})


def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article': article})

@login_required(login_url='/accounts/login/')
def article_create(request):
    if request.method == 'POST':
        form =forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form': form})

djangonautic/views.py
from django.http import  HttpResponse
from django.shortcuts import render

def about(request):
    return render(request, "about.html")
    #return HttpResponse('hello')

def index(request):
    return render(request, "index.html")
    #return HttpResponse('home')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Zaloguj się</h1>
<form class="site-form" action="/accounts/login/" method="post">
    {% csrf_token %}
    {{ login_var }}
    {% if request.GET.next  %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <input type="submit" value="Log in">

</form>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Zarejestruj się</h1>

    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-article">
        <h2>Stwórz nowy wpis</h2>
        <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <img src="{{ article.thumb.url }}" />
        <h2>{{ article.title }}</h2>
        <h3>Autor:  {{ article.author.username }}</h3>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Wpisy</h1>
<div class="articles">
    {% for article in articles %}
    <div class="article">
        <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
        <p>{{ article.snippet }}</p>
        <p>{{ article.date }}</p>
        <p class="author">autor: {{ article.author.username }}</p>

    </div>

    {% endfor %}


</div>
{% endblock %}

templates/about.html
<html>
    <head>
<title>About</title>
    </head>
    <body>


    </body>
</html>

templates/base_layout.html
{% load static from static %}
<html>
    <head>
        <meta charset="utf-8">
        <title>Blog</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body>
        <header class="wrapper">
            <h1><a href="{% url 'home' %}"><img src="{% static 'zydek.png' %}" alt="djangonautic" /></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Wyloguj się</button>
                        </form>
                    </li>
                    <li><a href="{% url 'articles:create' %}" class="highlight">Dodaj wpis</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Zaloguj się</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Zarejestruj się</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

templates/index.html
<html>
    <head>
<title>Homepage</title>
    </head>
    <body>


    </body>
</html>